/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/webhooks/user-created": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** User Created */
    post: operations["webhooks_user_created"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/user-updated": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** User Updated */
    post: operations["webhooks_user_updated"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/user-deleted": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** User Deleted */
    post: operations["webhooks_user_deleted"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["auth_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stats */
    get: operations["admin_stats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/students": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Students */
    get: operations["admin_students"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Applications */
    get: operations["admin_applications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/universities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Universities */
    get: operations["admin_universities_list"];
    put?: never;
    /** Create University */
    post: operations["admin_universities_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/universities/{university_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update University */
    patch: operations["admin_universities_update"];
    trace?: never;
  };
  "/account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Account */
    delete: operations["account_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile */
    get: operations["profiles_get"];
    put?: never;
    /** Create Profile */
    post: operations["profiles_create"];
    delete?: never;
    options?: never;
    head?: never;
    /** Update Profile */
    patch: operations["profiles_update"];
    trace?: never;
  };
  "/academic-records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Academic Record */
    get: operations["academic_records_get"];
    put?: never;
    /** Create Academic Record */
    post: operations["academic_records_create"];
    delete?: never;
    options?: never;
    head?: never;
    /** Update Academic Record */
    patch: operations["academic_records_update"];
    trace?: never;
  };
  "/contacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Contacts */
    get: operations["contacts_list"];
    put?: never;
    /** Upsert Contact */
    post: operations["contacts_upsert"];
    /** Delete Contact */
    delete: operations["contacts_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Document */
    post: operations["documents_upload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Documents */
    get: operations["documents_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Document */
    delete: operations["documents_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/universities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Universities */
    get: operations["universities_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/universities/{university_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get University */
    get: operations["universities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/universities/{university_id}/programmes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List University Programmes */
    get: operations["universities_programmes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recommendations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Recommendations */
    get: operations["recommendations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/careers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Careers */
    get: operations["careers_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/careers/{career_id}/programmes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Career Programmes */
    get: operations["careers_programmes_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Applications */
    get: operations["applications_list"];
    put?: never;
    /** Create Application */
    post: operations["applications_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Application */
    get: operations["applications_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/field-mappings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Field Mapping */
    get: operations["applications_field_mappings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record Consent */
    post: operations["applications_consent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/challenge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Supply Challenge
     * @description Answer the pending email challenge the automation run is waiting on
     *     (status `action_required`) — e.g. the OTP the portal emailed the student.
     */
    post: operations["applications_supply_challenge"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/applications/{application_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry Application */
    post: operations["applications_retry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /** Service Ping */
    head: operations["service_ping_ping_head"];
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AcademicRecordCreate */
    AcademicRecordCreate: {
      /** @default grade_11_final */
      record_type: components["schemas"]["RecordType"];
      /** Institution */
      institution: string;
      /** Year */
      year: number;
      /** Subjects */
      subjects: components["schemas"]["SubjectIn"][];
    };
    /** AcademicRecordPatch */
    AcademicRecordPatch: {
      /** Institution */
      institution?: string | null;
      /** Year */
      year?: number | null;
      /** Subjects */
      subjects?: components["schemas"]["SubjectIn"][] | null;
    };
    /** AcademicRecordResponse */
    AcademicRecordResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Student Id
       * Format: uuid
       */
      student_id: string;
      record_type: components["schemas"]["RecordType"];
      /** Institution */
      institution: string;
      /** Year */
      year: number;
      /** Subjects */
      subjects: components["schemas"]["SubjectOut"][];
      /** Aggregate */
      aggregate?: number | null;
    };
    /** AdminApplicationRow */
    AdminApplicationRow: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Student Email */
      student_email: string;
      /** Student Name */
      student_name: string | null;
      /** University Name */
      university_name: string;
      /** Programme */
      programme: string;
      /** Status */
      status: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AdminApplicationsResponse */
    AdminApplicationsResponse: {
      /** Items */
      items: components["schemas"]["AdminApplicationRow"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Per Page */
      per_page: number;
    };
    /** AdminStatsResponse */
    AdminStatsResponse: {
      /** Total Students */
      total_students: number;
      /** Active Universities */
      active_universities: number;
      /** Applications By Status */
      applications_by_status: components["schemas"]["ApplicationStatusCount"][];
    };
    /** AdminStudentRow */
    AdminStudentRow: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string | null;
      /** Last Name */
      last_name: string | null;
      /** Profile Complete */
      profile_complete: boolean;
      /** Application Count */
      application_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AdminStudentsResponse */
    AdminStudentsResponse: {
      /** Items */
      items: components["schemas"]["AdminStudentRow"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Per Page */
      per_page: number;
    };
    /** ApplicationChoiceRead */
    ApplicationChoiceRead: {
      /** Choice Number */
      choice_number: number;
      /** Programme */
      programme: string;
      /** Programme Id */
      programme_id?: string | null;
      /** Eligible */
      eligible?: boolean | null;
    };
    /** ApplicationCreate */
    ApplicationCreate: {
      /**
       * University Id
       * Format: uuid
       */
      university_id: string;
      /** Programme */
      programme: string;
      /** Programme Id */
      programme_id?: string | null;
      /** Additional Programmes */
      additional_programmes?: string[] | null;
      /** Additional Programme Ids */
      additional_programme_ids?: string[] | null;
      /** Application Year */
      application_year: number;
    };
    /** ApplicationJobRead */
    ApplicationJobRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["ApplicationStatus"] | null;
      /** Attempts */
      attempts: number;
      /** Last Error */
      last_error: string | null;
      /** Screenshot Url */
      screenshot_url: string | null;
      /** Updated At */
      updated_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ApplicationRead */
    ApplicationRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Student Id
       * Format: uuid
       */
      student_id: string;
      /**
       * University Id
       * Format: uuid
       */
      university_id: string;
      /** Programme */
      programme: string;
      /** Programme Id */
      programme_id?: string | null;
      /** Application Year */
      application_year: number;
      status: components["schemas"]["ApplicationStatus"] | null;
      /** Submitted At */
      submitted_at: string | null;
      /** Updated At */
      updated_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Popi Consent At */
      popi_consent_at?: string | null;
      /** Agreement Consent At */
      agreement_consent_at?: string | null;
      latest_job?: components["schemas"]["ApplicationJobRead"] | null;
      /**
       * Choices
       * @default []
       */
      choices: components["schemas"]["ApplicationChoiceRead"][];
      pending_challenge?: components["schemas"]["PendingChallengeRead"] | null;
    };
    /**
     * ApplicationStatus
     * @enum {string}
     */
    ApplicationStatus:
      | "pending"
      | "processing"
      | "action_required"
      | "submitted"
      | "failed";
    /** ApplicationStatusCount */
    ApplicationStatusCount: {
      /** Status */
      status: string;
      /** Count */
      count: number;
    };
    /** Body_documents_upload */
    Body_documents_upload: {
      /** File */
      file: string;
      document_type: components["schemas"]["DocumentType"];
    };
    /** CareerProgrammeMatch */
    CareerProgrammeMatch: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Faculty */
      faculty?: string | null;
      /** Qualification Type */
      qualification_type?: string | null;
      /** Duration Years */
      duration_years?: number | null;
      /** Min Aps */
      min_aps?: number | null;
      /** Status */
      status: string;
      /**
       * Unmet Rules
       * @default []
       */
      unmet_rules: unknown[];
      /** Notes */
      notes?: string | null;
    };
    /** CareerProgrammesResponse */
    CareerProgrammesResponse: {
      /** Career Id */
      career_id: string;
      /** Career Title */
      career_title: string;
      /** Universities */
      universities: components["schemas"]["CareerUniversityGroup"][];
      /**
       * Tvet Only
       * @default false
       */
      tvet_only: boolean;
    };
    /** CareerRead */
    CareerRead: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Industry */
      industry: string;
      /** Description */
      description: string;
      compensation: components["schemas"]["CompensationOut"];
      employability: components["schemas"]["EmployabilityOut"];
      /**
       * Required Subjects
       * @default []
       */
      required_subjects: string[];
    };
    /** CareerUniversityGroup */
    CareerUniversityGroup: {
      /** University Id */
      university_id: string;
      /** University Name */
      university_name: string;
      /** Scoring Method */
      scoring_method?: string | null;
      /** Aps */
      aps: number;
      /** Aps Max */
      aps_max: number;
      /** Programmes */
      programmes: components["schemas"]["CareerProgrammeMatch"][];
    };
    /** CareersListResponse */
    CareersListResponse: {
      /** Careers */
      careers: components["schemas"]["CareerRead"][];
    };
    /**
     * ChallengeSupplyRequest
     * @description The student's answer to a pending challenge: one value per requested
     *     field name (extra keys are ignored, missing ones are a 422).
     */
    ChallengeSupplyRequest: {
      /** Values */
      values: {
        [key: string]: string;
      };
    };
    /** CompensationOut */
    CompensationOut: {
      /** Entry */
      entry: number;
      /** Mid */
      mid: number;
      /** Senior */
      senior: number;
      /** Currency */
      currency: string;
      /** Period */
      period: string;
      /** Display */
      display: string;
    };
    /**
     * ConsentRequest
     * @description Records the student's explicit acceptance after they've viewed the portal's
     *     POPI notice / application agreement (surfaced by the frontend). At least one
     *     must be true.
     */
    ConsentRequest: {
      /**
       * Popi
       * @default false
       */
      popi: boolean;
      /**
       * Agreement
       * @default false
       */
      agreement: boolean;
    };
    /** ContactResponse */
    ContactResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Student Id
       * Format: uuid
       */
      student_id: string;
      contact_type: components["schemas"]["ContactType"];
      /** Title */
      title?: string | null;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Relationship */
      relationship?: string | null;
      /** Id Number */
      id_number?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Street Address */
      street_address?: string | null;
      /** Suburb */
      suburb?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * ContactType
     * @description One captured contact covers all portals (the automation layer resolves
     *     roles through fallback chains) — the frontend should ask for ONE
     *     parent/guardian and offer a separate fee payer only as an opt-in
     *     ("someone else pays my fees"); never ask for an emergency contact
     *     (no portal needs a distinct person — Wits copies the next of kin).
     * @enum {string}
     */
    ContactType: "next_of_kin" | "fee_payer" | "guardian" | "emergency";
    /** ContactWrite */
    ContactWrite: {
      contact_type: components["schemas"]["ContactType"];
      /** Title */
      title?: string | null;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Relationship */
      relationship?: string | null;
      /** Id Number */
      id_number?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Street Address */
      street_address?: string | null;
      /** Suburb */
      suburb?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Postal Code */
      postal_code?: string | null;
    };
    /**
     * CurrentActivityEnum
     * @enum {string}
     */
    CurrentActivityEnum:
      | "Currently in Grade 12"
      | "Upgrading matric"
      | "Gap year"
      | "Employed"
      | "At university"
      | "Other";
    /**
     * DisabilityEnum
     * @enum {string}
     */
    DisabilityEnum:
      | "None"
      | "Visual impairment"
      | "Hearing impairment"
      | "Physical/mobility impairment"
      | "Intellectual disability"
      | "Learning disability"
      | "Mental health condition"
      | "Other";
    /** DocumentResponse */
    DocumentResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Student Id
       * Format: uuid
       */
      student_id: string;
      type: components["schemas"]["DocumentType"];
      /** Storage Url */
      storage_url: string;
      /** Original Filename */
      original_filename?: string | null;
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
    };
    /**
     * DocumentType
     * @enum {string}
     */
    DocumentType:
      | "ID_COPY"
      | "MATRIC_RESULTS"
      | "TRANSCRIPT"
      | "GRADE12_APRIL"
      | "GRADE11_RESULTS";
    /** EmployabilityOut */
    EmployabilityOut: {
      /** Demand */
      demand: string;
      /** Outlook */
      outlook: string;
      /** Pathways */
      pathways: string[];
      /** Employment Note */
      employment_note?: string | null;
    };
    /**
     * EthnicityEnum
     * @enum {string}
     */
    EthnicityEnum:
      | "African"
      | "Coloured"
      | "Indian"
      | "Asian"
      | "White"
      | "Other";
    /** FacultyGroup */
    FacultyGroup: {
      /** Faculty Id */
      faculty_id: string;
      /** Faculty Name */
      faculty_name: string;
      /** Close Date */
      close_date: string | null;
      /** Programmes */
      programmes: components["schemas"]["ProgrammeCatalogueItem"][];
    };
    /**
     * FieldMappingEntryRead
     * @description One mapped field for the review screen. `flagged` == low confidence
     *     (below the threshold in force when the mapping was produced).
     */
    FieldMappingEntryRead: {
      /** Field Id */
      field_id: string;
      /** Value */
      value?: string | null;
      /** Confidence */
      confidence: number;
      /** Flagged */
      flagged: boolean;
      /**
       * Reasoning
       * @default
       */
      reasoning: string;
      /** Source Profile Field */
      source_profile_field?: string | null;
    };
    /** FieldMappingRead */
    FieldMappingRead: {
      /**
       * Application Id
       * Format: uuid
       */
      application_id: string;
      /**
       * University Id
       * Format: uuid
       */
      university_id: string;
      /** Overall Confidence */
      overall_confidence: number;
      /** Confidence Threshold */
      confidence_threshold: number;
      /** Entries */
      entries: components["schemas"]["FieldMappingEntryRead"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * GenderEnum
     * @enum {string}
     */
    GenderEnum: "Male" | "Female";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HomeLanguageEnum
     * @enum {string}
     */
    HomeLanguageEnum:
      | "English"
      | "Afrikaans"
      | "isiZulu"
      | "isiXhosa"
      | "Sesotho"
      | "Setswana"
      | "Sepedi"
      | "Tshivenda"
      | "Xitsonga"
      | "siSwati"
      | "isiNdebele";
    /**
     * MaritalStatusEnum
     * @enum {string}
     */
    MaritalStatusEnum: "Single" | "Married" | "Divorced" | "Widowed" | "Other";
    /**
     * MatchStatus
     * @enum {string}
     */
    MatchStatus: "qualifies" | "borderline" | "not_yet";
    /**
     * PendingChallengeRead
     * @description An unanswered email challenge the run is waiting on — non-null while the
     *     status is `action_required`. The app shows one input per requested field
     *     (e.g. ["otp"], or ["temp_id", "password"]) and posts the values to
     *     /applications/{id}/challenge.
     */
    PendingChallengeRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Portal Slug */
      portal_slug: string;
      /** Requested Fields */
      requested_fields: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProgrammeCatalogueItem */
    ProgrammeCatalogueItem: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Qualification Code */
      qualification_code: string | null;
      /** Qualification Type */
      qualification_type?: string | null;
      /** Duration Years */
      duration_years?: number | null;
      /** Min Aps */
      min_aps: number | null;
      /** Notes */
      notes: string | null;
      combination?: components["schemas"]["ProgrammeCombination"] | null;
    };
    /** ProgrammeCombination */
    ProgrammeCombination: {
      /** Majors Min */
      majors_min?: number | null;
      /** Majors Max */
      majors_max?: number | null;
      /** Co Majors */
      co_majors?: string[] | null;
      /** Excludes */
      excludes?: string[] | null;
      /** Rule */
      rule?: string | null;
    };
    /** ProgrammeMatch */
    ProgrammeMatch: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Faculty */
      faculty: string | null;
      /** Qualification Code */
      qualification_code: string | null;
      /** Qualification Type */
      qualification_type?: string | null;
      /** Duration Years */
      duration_years?: number | null;
      /** Min Aps */
      min_aps: number | null;
      status: components["schemas"]["MatchStatus"];
      /** Unmet Rules */
      unmet_rules: components["schemas"]["UnmetRule"][];
      /** Notes */
      notes: string | null;
      combination?: components["schemas"]["ProgrammeCombination"] | null;
    };
    /** ProgrammesCatalogueResponse */
    ProgrammesCatalogueResponse: {
      /** University Id */
      university_id: string;
      /** Intake Year */
      intake_year: number;
      /** Faculties */
      faculties: components["schemas"]["FacultyGroup"][];
    };
    /** RecommendationsResponse */
    RecommendationsResponse: {
      /** University Id */
      university_id: string;
      /** Intake Year */
      intake_year: number;
      /** Record Type Used */
      record_type_used: string;
      /** Aps */
      aps: number;
      /** Aps Max */
      aps_max: number;
      /** Programmes */
      programmes: components["schemas"]["ProgrammeMatch"][];
    };
    /**
     * RecordType
     * @enum {string}
     */
    RecordType:
      | "grade_11_final"
      | "grade_12_april"
      | "grade_12_june"
      | "grade_12_final";
    /**
     * ReligionEnum
     * @enum {string}
     */
    ReligionEnum:
      | "None"
      | "Christianity"
      | "Islam"
      | "Hinduism"
      | "Judaism"
      | "African Traditional Religion"
      | "Buddhism"
      | "Other";
    /** StudentProfileResponse */
    StudentProfileResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      title?: components["schemas"]["TitleEnum"] | null;
      /** First Name */
      first_name?: string | null;
      /** Middle Names */
      middle_names?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Maiden Name */
      maiden_name?: string | null;
      /** Preferred Name */
      preferred_name?: string | null;
      /** Id Number */
      id_number?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Phone */
      phone?: string | null;
      /** Street Address */
      street_address?: string | null;
      /** Suburb */
      suburb?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Mailing Same As Residential */
      mailing_same_as_residential?: boolean | null;
      /** Mailing Street Address */
      mailing_street_address?: string | null;
      /** Mailing Suburb */
      mailing_suburb?: string | null;
      /** Mailing City */
      mailing_city?: string | null;
      /** Mailing Province */
      mailing_province?: string | null;
      /** Mailing Postal Code */
      mailing_postal_code?: string | null;
      /** Nationality */
      nationality?: string | null;
      /** Is Sa Citizen */
      is_sa_citizen?: boolean | null;
      gender?: components["schemas"]["GenderEnum"] | null;
      home_language?: components["schemas"]["HomeLanguageEnum"] | null;
      religion?: components["schemas"]["ReligionEnum"] | null;
      disability?: components["schemas"]["DisabilityEnum"] | null;
      /** Disability Detail */
      disability_detail?: string | null;
      /** Disability Assistance */
      disability_assistance?: string | null;
      marital_status?: components["schemas"]["MaritalStatusEnum"] | null;
      ethnicity?: components["schemas"]["EthnicityEnum"] | null;
      current_activity?: components["schemas"]["CurrentActivityEnum"] | null;
      /** Exam Number */
      exam_number?: string | null;
      /** Sport */
      sport?: string | null;
      /** Wants Residence */
      wants_residence?: boolean | null;
      /** Preferred Residence */
      preferred_residence?: string | null;
      /** Applying Nsfas */
      applying_nsfas?: boolean | null;
      /** Applying Institutional Funding */
      applying_institutional_funding?: boolean | null;
      /** Nbt Reference */
      nbt_reference?: string | null;
      /** Nbt Year */
      nbt_year?: number | null;
      /** Nbt Date */
      nbt_date?: string | null;
      /** Redress Factors */
      redress_factors?: {
        [key: string]: unknown;
      } | null;
      /** Updated At */
      updated_at?: string | null;
      /** Is Complete */
      readonly is_complete: boolean;
    };
    /** StudentProfileWrite */
    StudentProfileWrite: {
      title?: components["schemas"]["TitleEnum"] | null;
      /** First Name */
      first_name?: string | null;
      /** Middle Names */
      middle_names?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Maiden Name */
      maiden_name?: string | null;
      /** Preferred Name */
      preferred_name?: string | null;
      /** Id Number */
      id_number?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Phone */
      phone?: string | null;
      /** Street Address */
      street_address?: string | null;
      /** Suburb */
      suburb?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Mailing Same As Residential */
      mailing_same_as_residential?: boolean | null;
      /** Mailing Street Address */
      mailing_street_address?: string | null;
      /** Mailing Suburb */
      mailing_suburb?: string | null;
      /** Mailing City */
      mailing_city?: string | null;
      /** Mailing Province */
      mailing_province?: string | null;
      /** Mailing Postal Code */
      mailing_postal_code?: string | null;
      /** Nationality */
      nationality?: string | null;
      /** Is Sa Citizen */
      is_sa_citizen?: boolean | null;
      gender?: components["schemas"]["GenderEnum"] | null;
      home_language?: components["schemas"]["HomeLanguageEnum"] | null;
      religion?: components["schemas"]["ReligionEnum"] | null;
      disability?: components["schemas"]["DisabilityEnum"] | null;
      /** Disability Detail */
      disability_detail?: string | null;
      /** Disability Assistance */
      disability_assistance?: string | null;
      marital_status?: components["schemas"]["MaritalStatusEnum"] | null;
      ethnicity?: components["schemas"]["EthnicityEnum"] | null;
      current_activity?: components["schemas"]["CurrentActivityEnum"] | null;
      /** Exam Number */
      exam_number?: string | null;
      /** Sport */
      sport?: string | null;
      /** Wants Residence */
      wants_residence?: boolean | null;
      /** Preferred Residence */
      preferred_residence?: string | null;
      /** Applying Nsfas */
      applying_nsfas?: boolean | null;
      /** Applying Institutional Funding */
      applying_institutional_funding?: boolean | null;
      /** Nbt Reference */
      nbt_reference?: string | null;
      /** Nbt Year */
      nbt_year?: number | null;
      /** Nbt Date */
      nbt_date?: string | null;
      /** Redress Factors */
      redress_factors?: {
        [key: string]: unknown;
      } | null;
    };
    /** SubjectIn */
    SubjectIn: {
      /** Name */
      name: string;
      /** Mark */
      mark: number;
      /** Nsc Level */
      nsc_level?: number | null;
      /** Custom Name */
      custom_name?: string | null;
    };
    /** SubjectOut */
    SubjectOut: {
      /** Name */
      name: string;
      /** Mark */
      mark: number;
      /** Nsc Level */
      nsc_level?: number | null;
      /** Custom Name */
      custom_name?: string | null;
    };
    /**
     * TitleEnum
     * @enum {string}
     */
    TitleEnum: "Mr" | "Mrs" | "Ms" | "Miss" | "Dr" | "Prof" | "Mx" | "Other";
    /** UniversitiesListResponse */
    UniversitiesListResponse: {
      /** Items */
      items: components["schemas"]["UniversityRead"][];
    };
    /** UniversityCreate */
    UniversityCreate: {
      /** Name */
      name: string;
      /** Website */
      website: string;
      /** Portal Url */
      portal_url: string;
      /** Open Date */
      open_date?: string | null;
      /** Close Date */
      close_date?: string | null;
      /**
       * Is Active
       * @default false
       */
      is_active: boolean;
      /** Scoring Method */
      scoring_method?: string | null;
    };
    /** UniversityRead */
    UniversityRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Website */
      website: string;
      /** Portal Url */
      portal_url: string;
      /** Open Date */
      open_date?: string | null;
      /** Close Date */
      close_date?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Scoring Method */
      scoring_method?: string | null;
    };
    /** UniversityUpdate */
    UniversityUpdate: {
      /** Name */
      name?: string | null;
      /** Website */
      website?: string | null;
      /** Portal Url */
      portal_url?: string | null;
      /** Open Date */
      open_date?: string | null;
      /** Close Date */
      close_date?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Scoring Method */
      scoring_method?: string | null;
    };
    /** UnmetRule */
    UnmetRule: {
      /** Requirement */
      requirement: string;
      /** Have */
      have: string;
      /** Shortfall */
      shortfall: string;
    };
    /** UserCreatedPayload */
    UserCreatedPayload: {
      record: components["schemas"]["UserCreatedRecord"];
    };
    /** UserCreatedRecord */
    UserCreatedRecord: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** UserDeletedPayload */
    UserDeletedPayload: {
      record: components["schemas"]["UserDeletedRecord"];
    };
    /** UserDeletedRecord */
    UserDeletedRecord: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Role */
      role: string;
    };
    /** UserUpdatedPayload */
    UserUpdatedPayload: {
      record: components["schemas"]["UserUpdatedRecord"];
    };
    /** UserUpdatedRecord */
    UserUpdatedRecord: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  webhooks_user_created: {
    parameters: {
      query?: never;
      header?: {
        "x-webhook-secret"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreatedPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  webhooks_user_updated: {
    parameters: {
      query?: never;
      header?: {
        "x-webhook-secret"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdatedPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  webhooks_user_deleted: {
    parameters: {
      query?: never;
      header?: {
        "x-webhook-secret"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserDeletedPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  admin_stats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminStatsResponse"];
        };
      };
    };
  };
  admin_students: {
    parameters: {
      query?: {
        page?: number;
        per_page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminStudentsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_applications: {
    parameters: {
      query?: {
        page?: number;
        per_page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminApplicationsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_universities_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UniversitiesListResponse"];
        };
      };
    };
  };
  admin_universities_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UniversityCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UniversityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_universities_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        university_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UniversityUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UniversityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  account_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  profiles_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudentProfileResponse"];
        };
      };
    };
  };
  profiles_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudentProfileWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudentProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  profiles_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudentProfileWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudentProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  academic_records_get: {
    parameters: {
      query?: {
        record_type?: components["schemas"]["RecordType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["AcademicRecordResponse"]
            | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  academic_records_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcademicRecordCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AcademicRecordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  academic_records_update: {
    parameters: {
      query?: {
        record_type?: components["schemas"]["RecordType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcademicRecordPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AcademicRecordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  contacts_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactResponse"][];
        };
      };
    };
  };
  contacts_upsert: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContactWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  contacts_delete: {
    parameters: {
      query: {
        contact_type: components["schemas"]["ContactType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_documents_upload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"][];
        };
      };
    };
  };
  documents_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  universities_list: {
    parameters: {
      query?: {
        q?: string | null;
        is_active?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UniversitiesListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  universities_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        university_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UniversityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  universities_programmes: {
    parameters: {
      query?: {
        intake_year?: number | null;
      };
      header?: never;
      path: {
        university_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgrammesCatalogueResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recommendations_get: {
    parameters: {
      query: {
        university_id: string;
        record_type?: string | null;
        intake_year?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecommendationsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  careers_list: {
    parameters: {
      query?: {
        intake_year?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CareersListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  careers_programmes_list: {
    parameters: {
      query?: {
        intake_year?: number | null;
      };
      header?: never;
      path: {
        career_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CareerProgrammesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRead"][];
        };
      };
    };
  };
  applications_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_field_mappings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldMappingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_consent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_supply_challenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChallengeSupplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  applications_retry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        application_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  service_ping_ping_head: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
