/**
 * uniflo-api — OpenAPI type definitions
 *
 * Generated by openapi-typescript from the FastAPI OpenAPI spec.
 * Do not edit by hand. To regenerate: npm run types:api
 *
 * API contract agreed with Partner B for Phase 1 + Phase 2.
 * See docs/phase-2/partner-a-phase-2-plan.md §"Before You Write a Single Line of Code"
 * for the full coordination checklist.
 */

// ─── Path definitions ────────────────────────────────────────────────────────

export interface paths {
  "/profile": {
    get: operations["get_profile"];
    put: operations["update_profile"];
  };

  "/academic-records": {
    get: operations["list_academic_records"];
    post: operations["create_academic_record"];
  };

  "/documents": {
    get: operations["list_documents"];
    post: operations["upload_document"];
  };

  "/universities": {
    get: operations["list_universities"];
  };

  "/universities/{id}": {
    parameters: {
      path: { id: string };
    };
    get: operations["get_university"];
  };

  "/applications": {
    get: operations["list_applications"];
    post: operations["create_application"];
  };

  "/applications/{id}": {
    parameters: {
      path: { id: string };
    };
    get: operations["get_application"];
  };

  "/applications/{id}/retry": {
    parameters: {
      path: { id: string };
    };
    post: operations["retry_application"];
  };
}

export type webhooks = Record<string, never>;

// ─── Component schemas ───────────────────────────────────────────────────────

export interface components {
  schemas: {
    // ── Profile ──────────────────────────────────────────────────────────────

    ProfileResponse: {
      first_name?: string | null;
      last_name?: string | null;
      id_number?: string | null;
      date_of_birth?: string | null;
      phone?: string | null;
      address?: string | null;
      nationality?: string | null;
      // Enum values locked with Partner B — drive Playwright portal automation.
      gender?: "male" | "female" | "other" | "prefer_not_to_say" | null;
      home_language?:
        | "zulu"
        | "xhosa"
        | "afrikaans"
        | "english"
        | "sepedi"
        | "tswana"
        | "sesotho"
        | "tsonga"
        | "swati"
        | "venda"
        | "ndebele"
        | null;
    };

    ProfileUpdate: {
      first_name?: string | null;
      last_name?: string | null;
      id_number?: string | null;
      date_of_birth?: string | null;
      phone?: string | null;
      address?: string | null;
      nationality?: string | null;
      gender?: "male" | "female" | "other" | "prefer_not_to_say" | null;
      home_language?:
        | "zulu"
        | "xhosa"
        | "afrikaans"
        | "english"
        | "sepedi"
        | "tswana"
        | "sesotho"
        | "tsonga"
        | "swati"
        | "venda"
        | "ndebele"
        | null;
    };

    // ── Academic records ─────────────────────────────────────────────────────

    // Locked JSON contract agreed with Partner B — do not change the shape
    // without coordinating. The backend field-mapping service parses this
    // structure exactly. "Other" entries carry custom_name; all others do not.
    SubjectRecord:
      | { name: string; mark: number }
      | { name: "Other"; custom_name: string; mark: number };

    AcademicRecord: {
      id: string;
      student_id: string;
      institution: string;
      year: number;
      aggregate: number;
      subjects: components["schemas"]["SubjectRecord"][];
    };

    AcademicRecordCreate: {
      institution: string;
      year: number;
      aggregate: number;
      subjects: components["schemas"]["SubjectRecord"][];
    };

    // ── Documents ────────────────────────────────────────────────────────────

    // storage_url is present in the API response but intentionally unused on
    // the frontend — raw Supabase Storage URLs must not be shown to the user.
    // See architecture-designs.md §13 (security constraints).
    Document: {
      id: string;
      student_id: string;
      type: "id_document" | "matric_results" | "transcripts";
      storage_url: string;
      uploaded_at: string;
    };

    DocumentUploadResponse: {
      id: string;
      type: "id_document" | "matric_results" | "transcripts";
      uploaded_at: string;
    };

    // ── Universities (Phase 2) ────────────────────────────────────────────────

    University: {
      id: string;
      name: string;
      website: string;
      portal_url: string;
      open_date: string;
      close_date: string;
      is_active: boolean;
    };

    UniversityList: {
      items: components["schemas"]["University"][];
    };

    // ── Applications (Phase 2) ────────────────────────────────────────────────

    ApplicationCreate: {
      university_id: string;
      programme: string;
      application_year: number;
    };

    // Enum locked with Partner B — see architecture-designs.md and
    // partner-a-phase-2-plan.md §"Lock the API shape".
    ApplicationStatus: "pending" | "processing" | "submitted" | "failed";

    ApplicationJob: {
      id: string;
      application_id: string;
      status: components["schemas"]["ApplicationStatus"];
      attempts: number;
      last_error: string | null;
      // screenshot_url is Phase 3 — guard usage behind a null check.
      screenshot_url: string | null;
      updated_at: string;
      created_at: string;
    };

    Application: {
      id: string;
      student_id: string;
      university_id: string;
      programme: string;
      application_year: number;
      status: components["schemas"]["ApplicationStatus"];
      submitted_at: string | null;
      updated_at: string;
      created_at: string;
    };

    // GET /applications returns this pre-joined shape so the dashboard can
    // render without a second round-trip per row. Confirmed with Partner B.
    ApplicationWithJob: components["schemas"]["Application"] & {
      latest_job: components["schemas"]["ApplicationJob"] | null;
    };

    ApplicationList: {
      items: components["schemas"]["ApplicationWithJob"][];
    };

    // ── Error ─────────────────────────────────────────────────────────────────

    // FastAPI validation and business logic errors surface a detail string.
    ErrorDetail: {
      detail: string;
    };
  };

  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

// ─── Operations ──────────────────────────────────────────────────────────────

export interface operations {
  // ── Profile ─────────────────────────────────────────────────────────────────

  get_profile: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ProfileResponse"];
        };
      };
      /** Profile not yet created — redirect to /profile/setup */
      404: { content: never };
      401: { content: never };
    };
  };

  update_profile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ProfileResponse"];
        };
      };
      401: { content: never };
      422: {
        content: {
          "application/json": components["schemas"]["ErrorDetail"];
        };
      };
    };
  };

  // ── Academic records ─────────────────────────────────────────────────────────

  list_academic_records: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AcademicRecord"][];
        };
      };
      401: { content: never };
    };
  };

  create_academic_record: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcademicRecordCreate"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AcademicRecord"];
        };
      };
      401: { content: never };
      422: {
        content: {
          "application/json": components["schemas"]["ErrorDetail"];
        };
      };
    };
  };

  // ── Documents ────────────────────────────────────────────────────────────────

  list_documents: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Document"][];
        };
      };
      401: { content: never };
    };
  };

  upload_document: {
    requestBody: {
      content: {
        "multipart/form-data": {
          file: Blob;
          type: "id_document" | "matric_results" | "transcripts";
        };
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DocumentUploadResponse"];
        };
      };
      401: { content: never };
      422: {
        content: {
          "application/json": components["schemas"]["ErrorDetail"];
        };
      };
    };
  };

  // ── Universities ─────────────────────────────────────────────────────────────

  list_universities: {
    parameters: {
      query?: {
        /** Free-text search against university name */
        q?: string;
        is_active?: boolean;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UniversityList"];
        };
      };
      401: { content: never };
    };
  };

  get_university: {
    parameters: {
      path: { id: string };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["University"];
        };
      };
      404: { content: never };
      401: { content: never };
    };
  };

  // ── Applications ─────────────────────────────────────────────────────────────

  list_applications: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApplicationList"];
        };
      };
      401: { content: never };
    };
  };

  create_application: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationCreate"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Application"];
        };
      };
      /** Application deadline has passed for this university */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDetail"];
        };
      };
      401: { content: never };
      422: {
        content: {
          "application/json": components["schemas"]["ErrorDetail"];
        };
      };
    };
  };

  get_application: {
    parameters: {
      path: { id: string };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ApplicationWithJob"];
        };
      };
      404: { content: never };
      401: { content: never };
    };
  };

  retry_application: {
    parameters: {
      path: { id: string };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Application"];
        };
      };
      404: { content: never };
      401: { content: never };
    };
  };
}
